vich_uploader:
    db_driver: orm

    mappings:
       cours_file:
           uri_prefix: /uploads/cours
           upload_destination: '%kernel.project_dir%/public/uploads/cours'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer       
       profil_image:
           uri_prefix: /uploads/users
           upload_destination: '%kernel.project_dir%/public/uploads/users'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
